/*
 *
 * CampaignPage constants
 *
 */
const APP_NAME = 'app/CreateCampaignPage';
export const DEFAULT_ACTION = 'app/CreateCampaignPage/DEFAULT_ACTION';
export const FETCH_LABELS = `${APP_NAME}/FETCH_LABELS`;
export const SET_LABELS = `${APP_NAME}/SET_LABELS`;
export const FETCH_WINNER_TEMPLATES = `${APP_NAME}/FETCH_WINNER_TEMPLATES`;
export const FETCH_THANKYOU_TEMPLATES = `${APP_NAME}/FETCH_THANKYOU_TEMPLATES`;
export const FETCH_FORMS = `${APP_NAME}/FETCH_FORMS`;
export const SET_WINNER_TEMPLATES = `${APP_NAME}/SET_WINNER_TEMPLATES`;
export const SET_THANKYOU_TEMPLATES = `${APP_NAME}/SET_THANKYOU_TEMPLATES`;
export const SET_LOSER_TEMPLATES = `${APP_NAME}/SET_LOSER_TEMPLATES`;
export const SET_FORM_COMPLETE_TEMPLATES = `${APP_NAME}/SET_FORM_COMPLETE_TEMPLATES`;
export const SET_FORMS = `${APP_NAME}/SET_FORMS`;
export const FETCH_TEMPLATES = `${APP_NAME}/FETCH_TEMPLATES`;
export const SUBMIT_CAMPAIGN = `${APP_NAME}/SUBMIT_CAMPAIGN`;
export const SET_ERRORS = `${APP_NAME}/SET_ERRORS`;
export const SET_CAMPAIGN_ID = `${APP_NAME}/SET_CAMPAIGN_ID`;
export const SET_CAMPAIGN_LIST = `${APP_NAME}/SET_CAMPAIGN_LIST`;
export const SET_LOADING = `${APP_NAME}/SET_LOADING`;
