namespace MyTube.Core.Domain.SysSettings.Enums
{

    public enum NameType
    {

        URL,
        SIGN_UP_CONFIRMATION_ROUTE,
        FORGOT_PASSWORD_CONFIRMATION_ROUTE,
        WATCH_PAID_CONTENT_VIDE_ROUTE,
        ARTIST_PAGE_ROUTE,
        ARTIST_PROFILE_ROUTE,
        USER_PROFILE_ROUTE,
        MY_PAGE_ROUTE,
        WEBINAR_SCHEDULE_LIVE_ROUTE,

        PAGE_SIZE_DEFAULT,
        PAGE_SIZE_MAXIMUM,

        SERVER_URL,
        SUPPORTED_FORMAT,

        WEBINAR_THUMBNAIL_SIZE,
        VIDEO_THUMBNAIL_SIZE,
        PROFILE_PICTURE_MAX_FILE_SIZE,

        HOST,
        PORT,
        MAIL_FROM,
        USER_NAME,
        PASSWORD,

        CURRENCY,
        SANDBOX,
        LIVE_URL,
        SANDBOX_URL,
        CLIENT_ID,
        SECRET,
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_DESCRIPTION,
        PLAN_NAME,
        PRODUCT_TYPE,
        GENERATE_TOKEN_ROUTE,
        CATALOGS_PRODUCTS_ROUTE,
        BILLING_PLANS_ROUTE,
        CAPTURE_ORDERPAYMENT_ROUTE,
        SUBSCRIPTION_DETAILS_ROUTE,
        SUBSCRIPTION_TRANSACTION_LIST_ROUTE,
        CREATE_ORDER_ROUTE,
        AUTHORIZE_ORDER_PAYMENT_ROUTE,
        CAPTURE_ORDER_PAYMENT_ROUTE,
        VOID_ORDER_PAYMENT_ROUTE,
        CREATE_SUBSCRIPTION_ROUTE,
        CREATE_WEBINAR_TOKEN_EXPIRATION,
        PAYMENTS_PAYOUTS_ROUTE,
        SENDER_BATCH_HEADER_EMAIL_SUBJECT,
        SENDER_BATCH_HEADER_EMAIL_MESSAGE,
        SENDER_BATCH_ID,
        SUBSCRIPTION_CANCEL_ROUTE,
        PAYMENT_REFUND_DETAILS_ROUTE,
        PAYMENT_REFUND_NOTE_TO_PAYER,
        PAYMENT_REFUND_ROUTE,
        SENDER_BATCH_HEADER_AUTO_PAY_EMAIL_MESSAGE,
        SENDER_BATCH_HEADER_AUTO_PAY_EMAIL_SUBJECT,
        SENDER_BATCH_ID_LENGTH_ARTIST_AUTO_PAYMENT,
        SENDER_BATCH_ID_LENGTH_ARTIST_MANUAL_PAYMENT,
        VOID_ORDERPAYMENT_ROUTE,



        WEBHOOK_AUTHORIZATION,
        WEBINAR_START_EVENT,
        WEBINAR_END_EVENT,
        DELETE_WEBINAR_ROUTE,
        LIST_USERS_ROUTE,
        LIST_WEBINARS_ROUTE,
        LIST_ALL_RECORDINGS_ROUTE,
        WEBINAR_DETAIL_ROUTE,
        GET_USER_ZOOM_ID_TOKEN_EXPIRATION,
        DELETE_WEBINAR_TOKEN_EXPIRATION,
        UPDATE_WEBINAR_ROUTE,
        WEBINAR_ZOOM_RECORDING_DOWNLOAD_TOKEN_EXPIRATION,
        WEBINAR_ZOOM_RECORDING_FETCH_TOKEN_EXPIRATION,


        UPLOAD_FOLDER_ADMIN,

        FFMPEG_APP_PATH_ADMIN,

        PAID_CONTENT_HASH_PREFIX,
        LIVE_TICKET_HASH_PREFIX,
        PAID_CONTENT_HASH_LENGTH,
        LIVE_TICKET_HASH_LENGTH,
        ARTIST_PAYPERVIEW_FEE,
        ARTIST_LIVETICKET_FEE,
        ARTIST_SUBSCRIPTION_FEE,


        ARTIST_PAYMENT_AGGREGATOR_CRON_RUN_SCHEDULE,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_FROM_MONTH,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_FROM_DAY,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_FROM_TIME,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_TO_MONTH,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_TO_DAY,
        ARTIST_PAYMENT_AGGREGATOR_CRON_CUTOFF_TO_TIME,


        ARTIST_PAYMENT_SENDER_CRON_RUN_SCHEDULE,
        ARTIST_PAYMENT_SENDER_CRON_RUN_SCHEDULE_FEBRUARY,

        ARTIST_PAYMENT_VERIFIER_CRON_RUN_SCHEDULE,

        WEBINAR_AUTO_DECLINER_CRON_RUN_SCHEDULE

    }

}
